### ISSUE TITLE
Feat: Better error log to showcase why solution failed for python.

### ISSUE THREAD

**Issue by sharmas1ddharth** [TimefoldAI/timefold-solver#1097]
**Is your feature request related to a problem? Please describe.**
It's really difficult to understand why solver failed as there is only solution failed text not the reason or exception

**Describe the solution you'd like**
It will be better if we get to see the exception or error causing solving failed

**Comment by triceo** [comment]
@sharmas1ddharth Thanks for the report!

We'd like to understand the situation in which this happens; we keep improving our error messages with every release. Please provide steps to reproduce your issue and we'll take a look when time permits.

**Comment by sharmas1ddharth** [comment]
In VRP optimisation,
I have 3 locations and one depot when fetching distance and duration from our custom distance time matrix.
first one is depot and other are locations.

locations_set1 = [Location(77.27926863862307, 28.5261602315649), Location(73.0578158, 19.2522977), Location(73.0578158, 19.2522977), Location(78.9475437, 25.7242883)]

locations_set2 = [Location(77.27926863862307, 28.5261602315649), Location(77.27926863862307, 28.5261602315649), Location(73.0578158, 19.2522977), Location(73.0578158, 19.2522977), Location(78.9475437, 25.7242883)]

locations_set2 contain depot location twice. but it is also not working when I do

locations_set3 = [Location(77.27926863862307, 28.5261602315649), Location(73.0578158, 19.2522977), Location(73.0578158, 19.2522977), Location(78.9475437, 25.7242883), Location(77.27926863862307, 28.5261602315649)]

locations_set1 and locations_set3 is not working and throwing solving failed but locations_set2 is working.

I hope you understand my issue, It will be helpful to know why solving is failing.
