### ISSUE TITLE
Feat: Max (min?) number of overlapping items at any point in time

### ISSUE THREAD

**Issue by mcimbora** [TimefoldAI/timefold-solver#1129]
It would be good to have an abstraction on the solver level (CS API) that allows me to express constraint "maximum n shifts at any given point in time".

This can be already done by defining helper intervals (e.g. 1 hour) and checking the number of overlaps with those intervals. For a long timeline, this is pretty much a time grain style, since we need to define the intervals to cover the whole timeline.

Motivation: At location X, there might be n pieces of equipment, we want to make sure we don't schedule more than n parallel shifts there.

**Comment by Christopher-Chianelli** [comment]
Already available via `toConnectedRanges`: https://github.com/TimefoldAI/timefold-solver/blob/459bfb6facb03f45a76607c3057a200b53d844f2/core/src/main/java/ai/timefold/solver/core/api/score/stream/ConstraintCollectors.java#L1962-L2001 ; see the docs for an example: https://docs.timefold.ai/timefold-solver/latest/constraints-and-score/score-calculation#collectorsConnectedRanges
