### ISSUE TITLE
Improve handling of sub pillar move sizes

### ISSUE THREAD

**Issue by jason076** [TimefoldAI/timefold-solver#1137]
**Is your feature request related to a problem? Please describe.**
At the moment configuring sub pillars always throw an UnsupportedOpperationException every step in DefaultPillarSelector.getSize(). Since this is an expected behaviour and exceptions have some overhead in java I would suggest not to raise an exception here since in fast stepping algorithms this exception is thrown very often. 

**Describe the solution you'd like**
Not raising an exception

**Comment by triceo** [comment]
Hello @jason076!

The existing selector mechanism is the oldest part of the solver there is - it's served us well for over a decade, but it can no longer be stretched to do the things we need to do, and now it's time to replace it with something better. 

We're working on that replacement as we speak - and among other things, that replacement will no longer have any `size`. However, it is a long-term project that will be introduced incrementally over the coming months, so please bear with us as we do.

We are no longer going to be making any updates to the move selector framework and when the replacement shows up, this entire piece of code will be deprecated for removal. Therefore I am closing this feature request.
