### ISSUE TITLE
Docs: License wording ambiguity in README

### ISSUE THREAD

**Issue by dacalabrese** [TimefoldAI/timefold-solver#1155]
Hi,

Thank you for this amazing project!

I'd like to suggest an improvement in the wording used to describe the `timefold-solver` licensing approach in the README.

[Here](https://github.com/TimefoldAI/timefold-solver/blob/main/README.adoc?plain=1#L82-L83), the open source license is described as `ASL`.
I'd rather use the `Apache-2.0` abbreviation (which is the OSI-approved SPDX ID) which eliminates any ambiguity referring to the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0).

If you agree I can implement the modification and raise a PR.

**Comment by triceo** [comment]
Thanks for reporting, @dacalabrese, and thanks for your kind words!
I provided a PR to address your comment - next time, maybe think about doing it yourself? We're open-source after all! ;-)
