### ISSUE TITLE
Docs: The quickstarts page is difficult to follow and contains outdated code

### ISSUE THREAD

**Issue by TomCools** [TimefoldAI/timefold-solver#1202]
### Discussed in https://github.com/TimefoldAI/timefold-solver/discussions/1175

<div type='discussions-op-text'>

<sup>Originally posted by **tomashauser** November  2, 2024</sup>
I tried following the [quarkus-quickstart](https://docs.timefold.ai/timefold-solver/latest/quickstart/quarkus/quarkus-quickstart) without the underlying code so that I could initially read through it, try out the steps, and then review the "solution." However, this proved challenging, as the article introduces pieces of code that use outdated APIs, and there are instances of code appearing without context. I tracked the issues I encountered so that the quickstart article can be improved. I also have a few suggestions.

1. In [this section](https://docs.timefold.ai/timefold-solver/latest/quickstart/quarkus/quarkus-quickstart#_the_build_file_and_the_dependencies), you can directly use a URL with preselected options:
    ```
    https://code.quarkus.io/?a=timefold-solver-quickstart&j=17&e=resteasy&e=resteasy-jackson&e=ai.timefold.solver%3Atimefold-solver-quarkus-jackson&e=ai.timefold.solver%3Atimefold-solver-quarkus
    ```
   This saves users from manually selecting options.

2. In multiline commands using a backward slash (`\`), add a note for Windows users to place the command on a single line if they use CMD.

3. In [this section](https://docs.timefold.ai/timefold-solver/latest/using-timefold-solver/modeling-planning-problems#planningValue), it says:
   _"Planning value ranges need to be countable, meaning there needs to be a finite number of possible planning values."_  
   This is not technically correct, as countability does not imply finiteness (for example, the set of natural numbers is countable but infinite). I would suggest saying that they need to come from a finite collection.

4. When reaching this step: [Create the Solver Service](https://docs.timefold.ai/timefold-solver/latest/quickstart/quarkus/quarkus-quickstart#_create_the_solver_service), the tutorial starts using `javax.ws.rs`, but newer versions of Quarkus will rightly complain that `jakarta` imports (e.g., `jakarta.inject.Inject`, `jakarta.ws.rs.POST`, `jakarta.ws.rs.Path`) should be used.

5. In [this section](https://docs.timefold.ai/timefold-solver/latest/quickstart/quarkus/quarkus-quickstart#_test_the_application), you call `TimetableConstraintProvider::roomConflict`, but in [this earlier section](https://docs.timefold.ai/timefold-solver/latest/quickstart/quarkus/quarkus-quickstart#_test_the_constraints), it was made a private method.

6. The code from the previous point is also invalid, as the room variable is named `ROOM`, not `ROOM1` as referenced in the `roomConflict` test. Additionally, the new `Lesson` object calls a constructor that wasn't defined in the `Lesson` class snippet.

7. In [Test the Solver](https://docs.timefold.ai/timefold-solver/latest/quickstart/quarkus/quarkus-quickstart#_test_the_solver), `jakarta.inject` is correctly used, but the constraint test before it still uses `javax` imports, which Quarkus does not accept.

8. The test in [this section](https://docs.timefold.ai/timefold-solver/latest/quickstart/quarkus/quarkus-quickstart#_test_the_solver) uses `org.awaitility`, which was not listed in the dependency list at the beginning of the tutorial.

9. Finally, the test in [Test the Solver](https://docs.timefold.ai/timefold-solver/latest/quickstart/quarkus/quarkus-quickstart#_test_the_solver) calls `.getSolverStatus`, which is not part of the `Timetable` definition. The user following this quickstart has no way of knowing the contents without downloading the quickstart project files. Additionally, there is mention of demo data that isn't explained elsewhere.
</div>

**Comment by TomCools** [comment]
1. Solved
2. Not solving, should be evident
3. Solved
4. Solved
5. Solved, by making a factory method in the test itself, instead of muddying the domain with an extra constructor
6. Solved
7. Solved
8. ... makes me wonder if telling people to test the solver through the Rest API should be the way to go. People who scroll to that test can get the impression that the "solver" also contains an API? To be discussed
9. I ran into this while making the Santa example, the domain and solution classes sometimes get extra details because the UI wants to show more (like solver status). My suggestion here would be to rework the quickstarts to have a separate RUN section (similar to how our models work). 

   - Run: solverstatus, start datetime, etc.
   - Solution: contains basically the class annotated with "@PlanningSolution"

**Comment by triceo** [comment]
@TomCools The idea here was that the quickstarts would be converted to use the Model SDK, through which we'd get the ultimate standardization. 

In the absence of the Model SDK, I'd say to not complicate the quickstarts. They don't need to show how to do all the things - they only need to show how to get started. Arguably `getSolverStatus()` is a great example of something that just shouldn't be part of a quickstart at all.

**Comment by TomCools** [comment]
@triceo , I'll just remove the getSolverStatus() from this quickstart for now and make another valuable test.

What is your opinion on the Awaitility? I feel like I need to remove it and see how we can test this in a different way.
This is not a "how to test APIs" quickstart/course.

**Comment by TomCools** [comment]
@triceo , this whole Quickstart stuff is messy. For example, the Kotlin examples create a REST API with GET and POST, the Java example only shows POST (which waits and returns the solution directly in that call). 

Fixing this is a larger effort. I have fixed the most pressing issues in this PR already. Will make a new ticket to align the Getting Started tutorials (which should be different from the "use-case quickstarts)

**Comment by triceo** [comment]
I agree that it's a larger effort, @TomCools.
