### ISSUE TITLE
docs: enable tab sync

### ISSUE THREAD

**Issue by TomCools** [TimefoldAI/timefold-solver#1205]
In the quickstarts, we often support multiple languages. At this time, someone using the non-default language must manually click the tab of the preferred language (ex. Kotlin or Python)

Setting **:tabs-sync-option:** will sync these tabs. After selecting Python on 1 tab, it will also select Python on all other tabs. See https://github.com/asciidoctor/asciidoctor-tabs for more details.

This increases the usability of our docs at a relatively low cost. We do need to align the naming of all our tabs, and create tabs even when Java/Kotlin have exactly the same content.

**Comment by ge0ffrey** [comment]
Yes! This is a serious paper cut.

**Comment by TomCools** [comment]
Already did this on a separate branch. @ge0ffrey. Will finish it up today. 😊
