### ISSUE TITLE
Recommended Fit API: for one unassigned entity, returns the Score delta for each planning value

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#123]
Use cases:

1. In Employee Scheduling, when a new Shift is created on a published schedule, quickly return a list with recommendations which Employee to assign, based on the hard and soft constraint scoring.
2. In Vehicle Routing, when a new Visit is added, quickly return a list of time window recommendations to assign, based on (a variant of) the hard and soft constraints of the VRP.

Requirements:
- a single facade method that is easy to use
- use of incremental score calculation
- score explanation of the score delta (#287)

Related, but different: score cards and decision tables

**Comment by niekvanderkooy** [comment]
I would like to reference the following StackOverflow question and discussion with @triceo : [link](https://stackoverflow.com/questions/76803188/timefold-construction-of-a-solution-when-initial-solution-is-already-feasabl/76803730?noredirect=1#comment135424211_76805347)

Use of incremental score calculation outside of a solver would solve the problem discussed there.

**Comment by triceo** [comment]
The initial version of this will be single-threaded.
