### ISSUE TITLE
Source code doesn't compile (macOS M2 chip, Java 17, Mvn 3.9)

### ISSUE THREAD

**Issue by TueChristensen** [TimefoldAI/timefold-solver#1241]
Downloaded the CE source code and tried to compile with 

`mvn clean package -Dquickly` (also tried with -Dquickly)

This fails in the 

`Timefold Solver core implementation ................ FAILURE `

with the error 

`Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:3.2.0:schemagen (schemagen) on project timefold-solver-core: JAXB errors arose while SchemaGen compiled sources to XML.`

**Expected behavior**
The project can compile

**Actual behavior**
Build failure with message "Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:3.2.0:schemagen (schemagen) on project timefold-solver-core: JAXB errors arose while SchemaGen compiled sources to XML"

**To Reproduce**
Link to a small reproducer or attach an archive containing the reproducer to the issue.
Alternatively, provide clear and concise steps to reproduce the behavior.

## Environment

Macbook Pro M2 (apple silicon)

**Timefold Solver Version or Git ref**: 

Tried on both main (2cf8b2830e197826258e13981ddbde9070df09dd) and tag v1.16.0

**Java**
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode)

**Mvn**
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /opt/homebrew/Cellar/maven/3.9.9/libexec
Java version: 17.0.6, vendor: Eclipse Adoptium, runtime: /Users/tuechristensen/.sdkman/candidates/java/17.0.6-tem
Default locale: en_DK, platform encoding: UTF-8
OS name: "mac os x", version: "15.1.1", arch: "aarch64", family: "mac"

**Output of `uname -a` or `ver`:**

24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020 arm64

## Additional information

The project also complains about a number of deprecated functions e.g.

```
 warning: [removal] asConstraint(java.lang.String,java.lang.String) in ai.timefold.solver.core.api.score.stream.ConstraintBuilder has been deprecated and marked for removal
                .asConstraint(constraintPackage, constraintName);

```

and 
```

[removal] ai.timefold.solver.core.api.solver.ProblemFactChange in ai.timefold.solver.core.api.solver has been deprecated and marked for removal
    boolean addProblemFactChanges(@NonNull List<ProblemFactChange<Solution_>> problemFactChangeList);

```
```

.solution.descriptor.DefaultShadowVariableMetaModel
    public ShadowVariableDescriptor<Solution_> variableDescriptor() {
                                               ^
  (return type of accessor method variableDescriptor() must match the type of record component variableDescriptor)
```

But this may not be related

**Comment by triceo** [comment]
Hello @TueChristensen, and thanks for reporting!

I am on Macbook Pro M3 and I have no issues compiling. (Neither has the CI, but that one is on x86.) The error you are describing is often a red herring, indicating an issue earlier in the build. 

Looking at the version of JDK you're using (17.0.6), it is quite a bit behind, even for the LTS branch. We run and test our code with the latest 17 LTS, as well as with the latest JDK 21 LTS, and the latest JDK. I wonder what would happen if you upgraded to latest JDK 17 (17.0.13).

Finally, the deprecations you are seeing are expected - Timefold Solver is very strict about backwards compatibility, and we _never_ remove public APIs in minor versions. The deprecations are an unfortunate result of that fact.

**Comment by TueChristensen** [comment]
Hi @triceo, 

Thanks for the speedy answer. 

I upgraded to the latest jdk 17 (Temurin 17.0.13) and now it works! Having developed java for the last 8 years I don't recall seeing such a vague error message being solved by a non-major upgrade of Java. 

Oh, well! On to testing timefold :)

**Comment by triceo** [comment]
I'm glad that you got it to work!
