### ISSUE TITLE
SolverManager/SolverFactory: allow overwriting the termination spend time per solver

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#150]
Without rebuilding the entire solverfactory.

Requirements:
- Allow termination spend time set per HTTP request

**Comment by greyhairredbear** [comment]
For the sake of completeness, we have this use case for the `SolverManger` class (see [this stackoverflow question](https://stackoverflow.com/questions/76927440/creating-a-new-solvermanager-for-each-user-request-to-enable-timeout-configurati/76927739#76927739)). 

Nice to know there are thoughts to add this feature 👍

**Comment by ge0ffrey** [comment]
We definitely intend to add this feature (no promises when). It will be added in Timefold Community as it's unrelated to high-scalability. Some of the prelimanary work (split Config from Factory objects) has been done some time ago.

**Comment by lawmwad123** [comment]
Timefold solver withFinalBestSolutionConsumer not called Spring Boot
