### ISSUE TITLE
Memory leak by LambdaBeanPropertyMemberAccessor (reported on OptaPlanner 9.38.0.Final)

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#152]
https://groups.google.com/g/optaplanner-dev/c/VhZWl-NdIS8/m/t8Yi7lceAAAJ?utm_medium=email&utm_source=footer

" I get OutOfMemoryError in Metaspace. Cause in 
org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor. This class generated and not unloaded from memory.
I use SolverFactory.create() for dynamic configuration (SolverConfig) with each new task.
At the moment I found a solution with use domain access GIZMO, but if use default (REFLECTION) i get memory leak.
I use last version optaplanner 9.38.0.final."

![image](https://github.com/TimefoldAI/timefold-solver/assets/176880/850586e0-545e-4980-9b13-5ef333fa75e8)

**Comment by triceo** [comment]
Since I am out of ideas, I asked the following StackOverflow question:
https://stackoverflow.com/questions/76593538/metaspace-leak-using-lambdametafactory

As you can see, I managed to isolate it entirely. It doesn't need Timefold at all for the problem to show up.

**Comment by triceo** [comment]
So, the consensus seems to be that this is a long-standing bug in the JDK, and that there is no workaround. This means we have two options: 

1. Keep lambda and the performance and the leak.
2. Switch to reflection, losing performance, fixing the leak.

To help with the decision-making, I've prepared some numbers from my decision factory benchmark:

| **_Example_**          	| **Reflection** 	| **Lambda** 	| **Diff** 	|
|------------------------	|----------------	|------------	|----------	|
| _cloudbalancing_       	|        6313206 	|    6798157 	|   92,8 % 	|
| _machinereassignment_  	|        1434773 	|    1542706 	|   93,0 % 	|
| _nqueens_              	|        5051325 	|    5698029 	|   88,7 % 	|
| _projectjobscheduling_ 	|        1709431 	|    1787506 	|   95,6 % 	|
| _tsp_                  	|        2290388 	|    2493087 	|   91,9 % 	|
| _vehiclerouting_       	|         137348 	|     147304 	|   93,2 % 	|

These numbers show that an `IncrementalScoreCalculator` loses 5 to 12 % of performance (as measured by score calculations per second) by switching to reflection. Note that this benchmark is not entirely realistic, as it removes most of the solver and only really measures incremental score calculation performance.

**Comment by triceo** [comment]
And the consensus changed, the bug was closed; the leak is not a leak and we shouldn't be using the API, which is not an API.

This leaves us with two options:

- Remove the use of the API and take the performance hit.
- Invent a classloader hack, so that the "leak" resolves itself when our classloader (not the application classloader!) gets thrown away.
