### ISSUE TITLE
Migration error:  Error resolving version for plugin '.recipeArtifactCoordinates=ai.timefold.solver:timefold-solver-migration' 

### ISSUE THREAD

**Issue by devcomcentric** [TimefoldAI/timefold-solver#16]
Error resolving version for plugin '.recipeArtifactCoordinates=ai.timefold.solver:timefold-solver-migration' from the repositories [local (C:\Users\suppo\.m2\repository), jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/), jboss-public-repository (https://repository.jboss.org/nexus/content/groups/public/), central (https://repo.maven.apache.org/maven2)]: Plugin not found in any plugin repository -> [Help 1]

![WhatsApp Image 2023-05-09 at 12 00 02 PM](https://user-images.githubusercontent.com/110361585/236991228-46e51a65-f73d-4286-af01-77a6b1d11e33.jpeg)

**Comment by ge0ffrey** [comment]
Thank you for reporting @devcomcentric .
 
Could you try running the command again, with out the backslashes (`\`) without a newline char?

![image](https://github.com/TimefoldAI/timefold-solver/assets/176880/d3eb01fa-0bf7-4659-bd87-c12bd8dceb31)

**Comment by ge0ffrey** [comment]
Fixed: the website command line is now Windows friendly.
It will appear here in 2 minutes: https://timefold.ai/blog/2023/optaplanner-fork/

Thanks again for reporting!
