### ISSUE TITLE
"The fact was never inserted, so it cannot update" on trivial problem when solver solves multiple problem instances.

### ISSUE THREAD

**Issue by thimmwork** [TimefoldAI/timefold-solver#176]
**Describe the bug**
I'm currently migrating a project from Optaplanner 8.32.0 to Timefold 0.8.39, and get stuck with unexpected behavior that seems to have been introduced in Bavet between Optaplanner 8.33.0 (good) and 8.34.0 (bad).
When running the solver, the construction heuristic succeeds, but in the local search phase I get the exception
"The fact (...) was never inserted, so it cannot update".

I'm solving a modified bin packing problem, and the problem instance is very simple, because it's basically a smoke test:
It has 1 bin and 1 item, so the construction heuristic already finds a feasible solution. The exception also occurs with several items as long as it's only one bin and all fit into the same bin.

My termination looks like this:
>         <termination>
>             <terminationCompositionStyle>OR</terminationCompositionStyle>
>             <millisecondsSpentLimit>5000</millisecondsSpentLimit>
>             <unimprovedMillisecondsSpentLimit>800</unimprovedMillisecondsSpentLimit>
>             
>         </termination>

I found a workaround by adding a bestScoreLimit with the soft score of 1 used bin, which works for my use case where all bins incur the same costs.

**Expected behavior**
The solver should terminate with a feasible solution.

**Actual behavior**
An exception is thrown:

> java.lang.IllegalStateException: The fact (Item(id=829bf1bd-4dd7-40e2-8e57-73821b86b365, articleId=54a45f66-dd6a-4478-b4c2-f16254314a05, title=title, requiredWeightInG=4, requiredVolumeInML=0, loadUnit=LoadUnit(id=47a3b102-d7ba-4a52-abbc-fd91963886c4, maxWeightInG=18000, maxVolumeInML=76, cost=100000), weightArticle=false, shelf=null, zone=null)) was never inserted, so it cannot update.
> 	at org.optaplanner.constraint.streams.bavet.uni.ForEachUniNode.update(ForEachUniNode.java:43)
> 	at org.optaplanner.constraint.streams.bavet.BavetConstraintSession.update(BavetConstraintSession.java:53)
> 	at org.optaplanner.constraint.streams.bavet.BavetConstraintStreamScoreDirector.afterVariableChanged(BavetConstraintStreamScoreDirector.java:115)
> 	at org.optaplanner.core.impl.score.director.AbstractScoreDirector.changeVariableFacade(AbstractScoreDirector.java:427)
> 	at org.optaplanner.core.impl.heuristic.selector.move.generic.PillarChangeMove.doMoveOnGenuineVariables(PillarChangeMove.java:81)
> 	at org.optaplanner.core.impl.heuristic.move.AbstractMove.doMoveOnly(AbstractMove.java:26)
> 	at org.optaplanner.core.impl.heuristic.move.AbstractMove.doMove(AbstractMove.java:20)
> 	at org.optaplanner.core.impl.heuristic.move.AbstractMove.doMove(AbstractMove.java:15)
> 	at org.optaplanner.core.impl.score.director.AbstractScoreDirector.doAndProcessMove(AbstractScoreDirector.java:207)
> 	at org.optaplanner.core.impl.localsearch.decider.LocalSearchDecider.doMove(LocalSearchDecider.java:117)
> 	at org.optaplanner.core.impl.localsearch.decider.LocalSearchDecider.decideNextStep(LocalSearchDecider.java:101)
> 	at org.optaplanner.core.impl.localsearch.DefaultLocalSearchPhase.solve(DefaultLocalSearchPhase.java:72)
> 	at org.optaplanner.core.impl.solver.AbstractSolver.runPhases(AbstractSolver.java:83)
> 	at org.optaplanner.core.impl.solver.DefaultSolver.solve(DefaultSolver.java:193)

**To Reproduce**
The interesting thing is that I'm not able to reproduce this in a unit test or in a single run of the test in my IDE.
The solver only throws the exception when I start it in the context of an integration test via maven failsafe plugin, that also spins up an Apache Kafka broker with testcontainers, and a Spring context, so I suspect it's only triggered when cpu load is high.

If requested, I could try to set up a minimal maven project with failsafe integration test with testcontainers etc. It would take me some time though.

## Environment

**Timefold Solver Version or Git ref**: 
Optaplanner 8.34.0 - 8.38.0. Timefold 0.8.39

**Output of `java -version`:**
tested with Java 17.0.6 and 17.0.7 Temurin

**Output of `uname -a` or `ver`:**
Darwin 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

## Additional information

My understanding of move selection is limited, but I assume there are no moves if there is only one bin, which might be part of the problem. I'd like to state that in my production use cases, 1-bin problem instances will very well occur, and I see value in being able to use Timefold's score calculation (both for feasibility and soft costs) for these instances as well. 

I'm open to suggestions how to further investigate the root of the problem.

**Comment by triceo** [comment]
This has all the marks of a score corrupton. Running with `FULL_ASSERT` on `NON_INTRUSIVE_FULL_ASSERT` would confirm that. If this is a score corruption, your workaround has not fixed it. It has simply avoided one situation where it occurs; they may be others.

Score corruptions can be caused by a bug in the solver, or by an incorrect implementation of constraints. Unfortunately, without seeing those constraints, I can not say which of the two it is. 

The way how score corruptions are investigated and fixed is running the solver with minimal set of constraints which reproduce the problem, and a minimal data set. It is typically quite a lot of work to get the solution to this state, involving plenty of trial and error. However, there is simply no other way.

If you provide source code that I can run to reproduce the issue, I can look into it.

**Comment by thimmwork** [comment]
Thank you for your quick response.
When I run it with environmentMode FULL_ASSERT the exception stays the same. Neither with nor without the workaround I get any hint towards score corruption.
I will try to prepare a sample project.

**Comment by triceo** [comment]
@thimmwork I looked a bit more into the code that triggers this exception, and I am starting to think that there may be an issue on your side.

See, the message says `... was never inserted, so it cannot update.` The code that throws this looks for the fact in `IdentityHashMap`. My original thinking was that there is something wrong with your equals/hashcode, but the `IdentityHashMap` rules that one out.

In fact, it points to pretty much the only conclusion I can draw from this: *you are, in fact, updating an object that you never inserted before.* I can not imagine a situation where the solver would do that on its own, and am now expecting something fishy in some of your custom variable listeners, problem fact changes etc.

**Comment by thimmwork** [comment]
Thank you, that's it. I didn't dig into the code. But I'm using Kotlin data classes to model the domain, and those come with generated equals/hashcode based on the classes' fields. So you're right, obviously the hashcode is changing when fields change.
I assume that equals/hashcode that only take the object's immutable id into account will solve the issue. I'll verify that.

**Comment by thimmwork** [comment]
Bad news: I replaced the kotlin classes with Java classes to no avail.

Good news: I managed to reproduce the issue with the cloud balancing example project.
Turns out it only occurs when solving multiple problem instances on the second test (that's why it didn't show up in my individual test runs, my Kafka test was polluted with another message). And the planning entity that "was never inserted" belongs to the first problem instance where solving already terminated.
So it's more a context pollution (or I'm using scoped objects in a wrong way).

Here's a minimal unit test. I integrated a minimal solver config in the java code:

`
package ai.timefold.solver.examples.cloudbalancing.app;

import ai.timefold.solver.core.api.solver.SolverFactory;
import ai.timefold.solver.core.config.localsearch.LocalSearchPhaseConfig;
import ai.timefold.solver.core.config.score.director.ScoreDirectorFactoryConfig;
import ai.timefold.solver.core.config.solver.SolverConfig;
import ai.timefold.solver.core.config.solver.termination.TerminationConfig;
import ai.timefold.solver.examples.cloudbalancing.domain.CloudBalance;
import ai.timefold.solver.examples.cloudbalancing.domain.CloudComputer;
import ai.timefold.solver.examples.cloudbalancing.domain.CloudProcess;
import ai.timefold.solver.examples.cloudbalancing.score.CloudBalancingConstraintProvider;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class ContextPollutionTest {
    protected SolverFactory<CloudBalance> buildSolverFactory() {
        SolverConfig solverConfig = SolverConfig.createFromXmlResource(CloudBalancingApp.SOLVER_CONFIG);
        new SolverConfig(this.getClass().getClassLoader())
                .withSolutionClass(CloudBalance.class)
                .withEntityClasses(CloudProcess.class)
                .withScoreDirectorFactory(new ScoreDirectorFactoryConfig()
                        .withConstraintProviderClass(CloudBalancingConstraintProvider.class)
                        .withInitializingScoreTrend("ONLY_DOWN"))
                .withTerminationConfig(new TerminationConfig()
                        .withUnimprovedMillisecondsSpentLimit(1000L)
                        .withBestScoreLimit("0hard/-50soft"))
                .withPhases(new LocalSearchPhaseConfig());
        return SolverFactory.create(solverConfig);
    }

    @Test
    public void Optaplanner_8_34_0_migration__The_fact_was_never_inserted_so_it_cannot_update() {
        final SolverFactory<CloudBalance> solverFactory = buildSolverFactory();
        var solver = solverFactory.buildSolver();

        var problem1 = new CloudBalance(
                1111L,
                List.of(new CloudComputer(1L, 4, 1024, 100, 50)),
                List.of(new CloudProcess(4711L, 1, 256, 10)));

        var result1 = solver.solve(problem1);

        assertEquals(result1.getId(), problem1.getId());

        var problem2 = new CloudBalance(
                2222L,
                List.of(new CloudComputer(2L, 4, 1024, 100, 50)),
                List.of(new CloudProcess(4722L, 1, 256, 10)));

        var result2 = solver.solve(problem2);

        assertEquals(result2.getId(), problem2.getId());
    }
}
`

You'll see that the call to solve(problem2) will fail with `java.lang.IllegalStateException: The fact (CloudProcess-4711) was never inserted, so it cannot update.` which isn't referenced in problem2.

**Comment by triceo** [comment]
Thanks for the code, @thimmwork! This should make it relatively simple for me to figure out what is going on. I'm adding this to my backlog.

**Comment by thimmwork** [comment]
Sorry, I messed up the solver config. I had changes in the underlying xml, and the code used the xml config instead of the java one.
I corrected the above snippet. And I'm running on the current main (commit 3c933937) snapshot.
Even though I use more sophisticated union move selector config in my project, I noticed that the error only occurs when pillarChangeMoveSelector is part of the config.

**Comment by triceo** [comment]
Ok, I can run it now. I'm confirming this is a bug, we simply forget to clean up the pillar cache when we leave the step scope. Easy fix.

This was missed because we typically don't reuse `Solver` instances, and when we did, we didn't also use pillar moves.

**Comment by triceo** [comment]
And I appreciate your time in providing the reproducer - without it, we may never have found the root cause.
