### ISSUE TITLE
Bi predicate triggers filtering() for bi tuple that will not survive

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#186]
```
.forEach(Foo)
.filter(foo -> foo.getValue != null)
.join(equal(Foo::getValue),
    filtering((a, b) -> a.getValue().getY() + b.getValue().getY() < 10)) // NPE because getValue() returns null
```

### Workaround

```
.forEach(Foo)
.filter(foo -> foo.getValue != null)
.join(equal(Foo::getValue))
.filter((a, b) -> a.getValue().getY() + b.getValue().getY() < 10)
```
at a small performance loss (due to allocation)

Or 

```
.forEach(Foo)
.filter(foo -> foo.getValue != null)
.join(equal(Foo::getValue),
    filtering((a, b) -> a.getValue() != null && b.getValue() != null
           && a.getValue().getY() + b.getValue().getY() < 10)) // NPE because getValue() returns null
```
at a cost of uglier code

### What happens

1. Fact A didn't make it through its uni filter. (A.value == null)
2. Fact B did make it through its uni filter. (B.value == "x")
3. Then the score was calculated.
4. Fact A and B both update.
5. Now fact A makes it through it's uni filter. (A.value == "x")
6. Fact B won't. (B.value == null)
7. But before that happens, A makes it to the join node, and B is still in de indexer for "x", so the bi predicate on the join node is called, **with A.value = "x" and B.value = null even though there is a uni filter making sure no (value == null) get through**. That is very surprising for users (think NPE, CCE, etc).
8. Later this bi tuple wouldn't survive when the B update goes through.
9. And if it would survive, the filter would be run _again_...

This issue is in Bavet but is not in CS-Drools.

### Why  run the filtering() before ensuring the tuple will survive?

To avoid allocation the tuple in memory. This brings performance and memory reduction.

### Requirements

- [ ] More unit testing in AbstractBiConstraintStreamTest around equals(), filtering(), including a reproducer and a check how many times the filter is called.
- [ ] a fix
- [ ] run turtle tests for validation

**Comment by ge0ffrey** [comment]
Proposal A) If the left (or right) uni tuple comes in and the right (or left) uni tuple is UPDATING/REMOVING, don't run the filter? Leave the bi tuple creation to the other side?
But... what if the bi tuple already exists? What if the other side aborts? Many questions :)

**Comment by triceo** [comment]
The reproducer can be further simplified to remove the `equal(...)` index. The following will also trigger the exception:

    forEach(TestdataEntity.class)
        .filter(a -> a.getValue() != null)
        .join(TestdataEntity.class,
            filtering((a, b) -> {
                if (a.getValue() == null) {
                    throw new IllegalStateException("Impossible state: value of A is null even though the filter should prevent it.");
                }
                return true;
         }))
