### ISSUE TITLE
OptaPlanner -> Timefold migration - maybe upgrade logging configuration too?

### ISSUE THREAD

**Issue by mcimbora** [TimefoldAI/timefold-solver#19]
I've got a standard maven project with `logback.xml` logging configuration located at `src/main/resources/logback.xml`.

Example file definition:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="consoleAppender" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%-12.12t] %-5p %m%n</pattern>
        </encoder>
    </appender>
    <logger name="org.optaplanner" level="debug"/>
    <root level="info">
        <appender-ref ref="consoleAppender" />
    </root>
</configuration>
```

Package `org.optaplanner` is not replaced by `ai.timefold` after the migration, meaning the debug logging is not enabled by default. Just a minor thing, but made me think the solver is stuck at first.

**Comment by ge0ffrey** [comment]
Good point, we currently only do logging categories in application.properties of Quarkus and spring. We should consider logback.xml too

**Comment by triceo** [comment]
After a short discussion with Geoffrey, we agreed to process logback.xml and logback-test.xml.
In principle, we agreed not to go over *all* user files - only those which we understand, such as Logback XML files.
