### ISSUE TITLE
Timefold migration failed on No signature of method : rewrite()

### ISSUE THREAD

**Issue by CrommVardek** [TimefoldAI/timefold-solver#199]
**Describe the bug**
Timefold migration does not works because rewrite method cannot be found (script fails)

**Expected behavior**
Timefold migration finishing without failing

**Actual behavior**
Failure after 1s

**To Reproduce**
Following the guide [here](https://timefold.ai/blog/2023/optaplanner-fork/#upgrade-from-optaplanner-to-timefold), we added the file upgrade-timefold.gradle at the root of the project (edited the content of the dependendy to `classpath("org.openrewrite:plugin:latest.release")` for the relevant line). 

Run `gradle -Dorg.gradle.jvmargs=-Xmx2G --init-script upgrade-timefold.gradle rewriteRun -DtimefoldSolverVersion=1.0.0 ;` command.

results in : 

```
FAILURE: Build failed with an exception.

* Where:
Initialization script 'D:\my-project\upgrade-timefold.gradle' line: 25

* What went wrong:
No signature of method: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.rewrite() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl) values: [ai.timefold.solver:timefold-solver-migration:1]
Possible solutions: wait(), wait(long), create(java.lang.Object), with(groovy.lang.Closure)
> Could not find method rewrite() for arguments [ai.timefold.solver:timefold-solver-migration:1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
```

## Environment

`gradle --v`

```
------------------------------------------------------------
Gradle 8.2.1
------------------------------------------------------------

Build time:   2023-07-10 12:12:35 UTC
Revision:     a38ec64d3c4612da9083cc506a1ccb212afeecaa

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.2 (Oracle Corporation 17.0.2+8-86)
OS:           Windows 10 10.0 amd64
```

**Comment by triceo** [comment]
Thanks for reporting!
We'll look into it when time permits. In the meantime, if you could check if it works with some older versions of Gradle, that'd be appreciated - I'm not sure we've even tested it against 8.2 yet.

**Comment by CrommVardek** [comment]
Same error with gradle version 7.6.2 and version 8.1.1

**Comment by triceo** [comment]
I've published an update to the script on the website.
Me and a colleague both independently verified that, with the new script, Gradle 8.2.1 no longer fails.

(The fix is to bring the rewrite plugin to v6.)

I am closing this issue; if you're still seeing issues, feel free to reopen.

**Comment by CrommVardek** [comment]
Thanks for the quick update on this issue.

So, I've tried it again with the new script but it was unsuccessful.

I've then tried it on an Ubuntu distribution (Just to make sure that this had nothing to do with Windows) on a "clean" environment, I still got the same error :

```bash
vardek@LAPTOP-116:~/path-omitted/myproject-planner$ curl https://timefold.ai/product/upgrade/upgrade-timefold.gradle > upgrade-timefold.gradle ; gradle -Dorg.gradle.jvmargs=-Xmx2G --init-script upgrade-timefold.gradle rewriteRun -DtimefoldSolverVersion=1.0.0 ; rm upgrade-timefold.gradle
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1092  100  1092    0     0   5628      0 --:--:-- --:--:-- --:--:--  5600

Welcome to Gradle 8.2.1!

Here are the highlights of this release:
 - Kotlin DSL: new reference documentation, assignment syntax by default
 - Kotlin DSL is now the default with Gradle init
 - Improved suggestions to resolve errors in console output
 - Reduced sync memory consumption

For more details see https://docs.gradle.org/8.2.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Initialization script '/home/vardek/path-omitted/myproject-planner/upgrade-timefold.gradle' line: 24

* What went wrong:
No signature of method: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.rewrite() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl) values: [ai.timefold.solver:timefold-solver-migration:1.0.0]
Possible solutions: wait(), wait(long), create(java.lang.Object), with(groovy.lang.Closure)
> Could not find method rewrite() for arguments [ai.timefold.solver:timefold-solver-migration:1.0.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 17s
```

Btw, here is the env info :

```
gradle --v

------------------------------------------------------------
Gradle 8.2.1
------------------------------------------------------------

Build time:   2023-07-10 12:12:35 UTC
Revision:     a38ec64d3c4612da9083cc506a1ccb212afeecaa

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          11.0.20 (Ubuntu 11.0.20+8-post-Ubuntu-1ubuntu120.04)
OS:           Linux 5.4.72-microsoft-standard-WSL2 amd64
```

**Comment by triceo** [comment]
Mine is

    ------------------------------------------------------------
    Gradle 8.2.1
    ------------------------------------------------------------

    Build time:   2023-07-10 12:12:35 UTC
    Revision:     a38ec64d3c4612da9083cc506a1ccb212afeecaa

    Kotlin:       1.8.20
    Groovy:       3.0.17
    Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
    JVM:          17.0.8 (Eclipse Adoptium 17.0.8+7)
    OS:           Linux 6.4.7-200.fc38.x86_64 amd64

That's identical to yours. I'm afraid I don't know how to help, this configuration works for me and for a colleague of mine.

**Comment by triceo** [comment]
Hmm, no, it is not identical. You are using JDK 11. Let me try that.

**Comment by triceo** [comment]
Ok, JDK 11 seems to be unrelated. (*Although if you're migrating to Timefold 1.0.0, JDK 11 is no longer supported.*)

Can you please make sure that the rewrite plugin your Gradle is using is *actually* `6.1.23`? The only way how I can explain the error you are seeing is if - somehow - the old 5.x version of the plugin is cached somewhere on your system.

**Comment by CrommVardek** [comment]
Anyway, I found the folder where the plugin is supposed to be, and indeed it is version 6.1.23

**Comment by triceo** [comment]
> I must admit I'm confused...

Same here.
 
> Would simply replace the dependencies from optaplanner to timefold be enough to migrate ? (I doubt it could be that simple)

No. :-( Packages changes, artifact GAVs... it's not rocket science, but it's a lot of typing.

**Comment by CrommVardek** [comment]
Ok, we will try to upgrade manually, in the coming weeks, as explained here : https://timefold.ai/blog/2023/optaplanner-fork/

I'll report back if the manual migration went well.

**Comment by CrommVardek** [comment]
Reporting back, I migrated manually to timefold successfully in less than an hour, so all in all it's good. 

Thanks for the quick replies and support !

**Comment by triceo** [comment]
@CrommVardek Happy to hear it worked out! And thanks for reporting the issue; we did make an update, even though for some reason it did not help you.
