### ISSUE TITLE
Feat: Throttling of listener calls from solver manager

### ISSUE THREAD

**Issue by mswiderski** [TimefoldAI/timefold-solver#248]
**Is your feature request related to a problem? Please describe.**
note problem as such but can cause too many updates when solver manager invokes listeners that must store data in 3rd party storage

**Describe the solution you'd like**
Configurable throttling mechanism on solver manager that allows to control the rate at which listeners are invoked with best/final solution

**Describe alternatives you've considered**
Handling throttling within the listener but that might not be good enough as solver might have better knowledge on when and what to send to listeners.

**Additional context**

**Comment by ge0ffrey** [comment]
Requirements given a throttling of 1 event per 5 seconds:
- Never 2 events within the timespan of 5 seconds.
- **Skip ahead.** Once a new event has been received, there is no point sending out an older event.
 Given event A at 0.1s, B at 0.2s, C at 0.3s, D at 5.1s, it would typically output A and D. This means B and C never make it the client.
 - **Delay but not eaten** An event that happens too early, must still be forwarded (unless it got skip ahead).
 Given event A at 0.1s, B at 0.2s, C at 0.3s and D at 999s, it should output A at 0.1s, C at 5.1s and D at 999s.

**Comment by ge0ffrey** [comment]
Doesn't that last case (4s termination) violate the first requirement?
Probably, we 'll need to make a decision there.

**Comment by nicksi** [comment]
I think second approach will be better. Let's assume that we have event A at 0.1s, B at 4.9s and  C at 999s. With skip ahead we won't see any improvement in solution till 999s as B will be skipped. If you use stored data to display intermediate solution to end-user and solution B is the first one feasable (hard score == 0) missing it will be bad for UX perspective.
