### ISSUE TITLE
Feat: Conversion from Optaplanner to Timefold also for Kotlin

### ISSUE THREAD

**Issue by fransah** [TimefoldAI/timefold-solver#260]
I want to migrate from Optaplanner to Timefold, but i have a kotlin codebase instead of a java codebase. Is it possible to also convert a kotlin codebase?

Maybe be able to add a mvn parameter to migrate a kotlin project

**Comment by triceo** [comment]
There appears to be Kotlin language support for OpenRewrite:
https://github.com/openrewrite/rewrite-kotlin/releases

That said, we haven't tried it yet. No idea if it works, or what hoops one has to jump through to make it work. Pull requests are welcome.

**Comment by ge0ffrey** [comment]
I wonder what happens if you just run the maven command (from the fork message) on the technology/kotlin-java dir in optaplanner-quickstarts. It might "just work". Or you might need to add "rewrite-kotlin" into the command lines extra artifacts.

@fransah Would you be willing to give that a try?

**Comment by fransah** [comment]
Didn´t have time yet for this. Migrated it manually. Wasn´t that big of a change. Will probably look later into it when migrating a larger project.
