### ISSUE TITLE
Misleading error message when cloning fails to create a new instance

### ISSUE THREAD

**Issue by marcotama** [TimefoldAI/timefold-solver#271]
**Describe the bug**
When the `FieldAccessingSolutionCloner` fails to construct an object, it throws an exception with message `"The class $CLAZZ should have a no-arg constructor to create a planning clone."`. However, construction can fail for other reasons, e.g. in my case, I initialize some fields based on other fields, and this failed when a certain collection was empty.

**Expected behavior**
A better error message, e.g. `"Failed to create a new instance of class $CLAZZ for the purpose of solution-cloning. This could be due to a missing no-arg constructor or some other error inside the logic of class $CLAZZ triggered by the no-arg constructor."`

**Actual behavior**
Describe clearly and concisely what actually happened.

**To Reproduce**
N/A

## Environment

**Timefold Solver Version or Git ref**: 1.1.0

**Output of `java -version`:** N/A

**Output of `uname -a` or `ver`:** N/A

## Additional information

N/A

**Comment by triceo** [comment]
Thanks for reporting, @marcotama!
Would you have an example source code of a class that failed to clone in this way?

**Comment by marcotama** [comment]
Hello!

Something like this (Kotlin).
When you create a new `TimeBlock` using the default constructor, the list of `Timeslot`s is empty and so `next()` throws a `NoSuchElementException`.

```kotlin
import java.time.DayOfWeek

@PlanningEntity
class Timeslot(
    @PlanningId
    val id: Int? = null,
    val name: String? = null,
    val dayOfWeek: DayOfWeek? = null,
    val startTime: LocalTime? = null,
    val endTime: LocalTime? = null,
)

class TimeBlock(
    @PlanningId
    val id: Int? = null,
    val name: String? = null,
    val allTimeslots: Set<Timeslot> = mutableSetOf(),
) {
    val day: DayOfWeek? = allTimeslots.map { it.dayOfWeek }.iterator().next()
}
```
