### ISSUE TITLE
ScoreExplanation.subtract(ScoreExplanation)

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#286]
When having a solved schedule, the user sometimes wants to make a manual change and the UI needs to clearly show the score impact of that manual change. The score delta basically.

For example, in school timetabling:

- we have a schedule with a score of 0hard/-2000soft in the UI.
- `ScoreExplenation before = SolutionManager.explain(...)`
- Lesson Math and French are swapped (not with a move, just directly in the solution)
- `ScoreExplenation after = SolutionManager.explain(...)`
- What is the score delta and justification delta between `before` and `after`?
- `diff = before.substract(after)`

This would be reusable in the FULL_ASSERT score corruption analysis too.

**Comment by ge0ffrey** [comment]
![image](https://github.com/TimefoldAI/timefold-solver/assets/176880/bbd4d2b5-d441-4de9-968f-70a72a302c1f)

**Comment by triceo** [comment]
After many cycles of refinement, this became `ScoreAnalysis.diff(ScoreAnalysis)`, where `ScoreAnalysis` is retrieved by a new method, `SolutionManager.analyze(...)`.
