### ISSUE TITLE
Recommended fit: provide "per constraint justification"

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#287]
but not "per constraint match justification" or "indictment justification", because those are Object (=> JSON pain)

**Comment by ge0ffrey** [comment]
![image](https://github.com/TimefoldAI/timefold-solver/assets/176880/d5d6c952-d3b6-42db-8e52-d4f7700adf4c)

**Comment by triceo** [comment]
Will reuse `ScoreAnalysis`, with constraint matching enabled by default.
Will be delivered as part of #123.
