### ISSUE TITLE
Feat: Add support for sumDouble and supporting functions for Double

### ISSUE THREAD

**Issue by deepamin1994** [TimefoldAI/timefold-solver#291]
**Is your feature request related to a problem? Please describe.**
Currently an attribute of Double type can't be summed/operated upon in a constraint creation stream. 

**Describe the solution you'd like**
Please add support for Double/ other data types.

**Describe alternatives you've considered**
Writing own sumDouble and other functions

**Additional context**

**Comment by triceo** [comment]
Thank you for reporting the issue!

Unfortunately, we will not be implementing this feature; `double` is intentionally omitted.
You can [read why](https://timefold.ai/docs/timefold-solver/latest/constraints-and-score/constraints-and-score.html#avoidFloatingPointNumbersInScoreCalculation).

If you absolutely need to, you can implement your own `sumDouble` by looking at the implementation of `sum` or `sumLong`. However, my recommendation is to avoid it and either use `BigDecimal` or fixed-point arithmetic.
