### ISSUE TITLE
Replace adoc legacy id style [[myID]] with new style

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#296]
see https://docs.asciidoctor.org/asciidoc/latest/attributes/id/#block-assignment

- [x] docs
- [x] readme (solver, quickstarts)
- [ ] orbit model docs? platform docs?

**Comment by triceo** [comment]
The new way doesn't seem to work either.
As a stop-gap, I changed stable quickstarts to use the default generated anchors.
