### ISSUE TITLE
Support 2 SolverManager instances in Quarkus with @Named

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#351]
Support this in Quarkus:

```
@Named("trainSolverManager")
SolverManager<TrainSchedule> ...;

@Named("driverSolverManager")
SolverManager<DriverSchedule> ...;
```

Requirements:

- Support injection of solver config, solver manager and solver factory.
- Named ones should not default to using `src/main/resources/solverConfig.xml`.
- Optionally, each has a separate `solverConfig.xml`, with that location defined in application.properties. 
- Similar behavior should also be implemented for Spring Boot, but using their type of annotations.

**Comment by cngotho** [comment]
I have faced a problem for which the natural problem-solving flow led to this. A service that could solve 2 planning solutions with some shared planning variables. I came across [this](https://stackoverflow.com/questions/63712863/how-can-we-use-multiple-constraintproviders-when-using-the-springboot-optaplann/63737303#63737303) to learn it is not the case.
