### ISSUE TITLE
Optionally allow BestSolutionEvents for new, equal score solutions too.

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#352]
For steps only. Not moves.

Proposal A) In BestSolutionRecaller support:
`boolean eventForEqualScoreToo = false;`

**How can that be turned on from SolverConfig?**

Proposal H) Introduce BestSolutionRecallerConfig
Proposal I) Just add the Boolean on SolverConfig 
Proposal J) Just add the Boolean on ScoreDirectorFactoryConfig

Exposing this in application.properties is out of scope (unless we get a lot of votes on this issue as a lot of people do use it).

**Comment by zhetao1116** [comment]
It is hard for outsiders to hack on BestSolutionRecaller although the hack inside BestSolutionRecaller sounds only to override  eventForEqualScoreToo to be true. Could we vote on getting this feature soon? Thanks in advance!

**Comment by triceo** [comment]
@zhetao1116 Thank you for your input. 

To better understand the requirement here - why is it important to you to catch all the best solutions, even though the score did not improve? Wouldn't it instead make more sense to introduce additional soft constraints to get rid of score traps and at the same time reduce the number of best solutions that equal?

**Comment by zhetao1116** [comment]
Hi @triceo! In our case, there might be several solutions all work(Even without violating any constraints). We want to get a list of them and present all of them to the user.
Besides, if we can know the history of the best solutions which might all violate some rules, we want to get these solutions and evaluate the ranking ourselves.

**Comment by triceo** [comment]
Thank you for the explanation, @zhetao1116. If you don't mind, I'll add one extra comment: 

If you evaluate rankings manually, write down the criteria you use. Why do you prefer A over B?
Once you understand that, write constraints to formalize that - tell the solver that *it* needs to prefer those too. At that point, you will no longer need to do manual work, and you will no longer need this feature.

**Comment by zhetao1116** [comment]
Hi @triceo !
Our main use case is that we want to return a list of best solutions to the user and user could pick up from these themselves.  So these solutions should have exact the same constraints with same weights.

**Comment by ge0ffrey** [comment]
I have come to realize this is most of the time not the right solution for the problem.

Users that ask for this feature typically actually need recommendedFit() xor simulation support (through constraint weight profiles). Pareto optimization is typically useless in practice.

**Comment by triceo** [comment]
I am closing this issue.
Feel free to reopen it if Geoffrey's answer isn't sufficient.

**Comment by zhetao1116** [comment]
Thanks, will try that out!

**Comment by zhetao1116** [comment]
hi @ge0ffrey @triceo !
I checked the doc of the recommendFit() method. But from my understanding, it sounds not a perfect case if we just want to record all the solutions with equal score. recommendFit() is aimed to solve the problem that after optimizing, if a new planning entity is added, how could we make faster optimizations to assign planning variables to the new planning entity. But in my case, I don't have new planning entity added. I just need the history of the problem solving process.
The proposals from @ge0ffrey all look good, but it sounds hard for me to hack it. Do you have some other suggestions on my issue? How could I make a hack on BestSolutionRecaller(I don't want to fork from your master branch to hack it)? Or could you give more insights on how to apply recommendFit() to fit into our use case?
Thanks!
