### ISSUE TITLE
Feat: merge two constraint streams 

### ISSUE THREAD

**Issue by mwotton** [TimefoldAI/timefold-solver#356]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to merge two constraint streams. In this case, I'm simulating an outer join, where (concretely) each employee has a number of shifts, and each shift gives some points. I want to penalise going under quota: this means that i need to detect the case when an employee has zero shifts, using something like this

	UniConstraintStream<Pair<Employee, Integer>> unassignedEmployeeStream = constraintFactory.from(Employee.class)
	    .ifNotExists(Shift.class, Joiners.equal(employee -> employee.getId(),
						    shift -> shift.getEmployeeId()))
	    .map( employee -> Pair.of(employee, 0));

I then need to merge that constraint stream with the stream of employees that have at least one shift assigned.

**Describe the solution you'd like**
```
	UniConstraintStream<Pair<Employee, Integer>> allEmployeesWithPointsStream = employeeStream.concatenate(unassignedEmployeeStream);
```

`union`/`concatenate` or something similar. I don't much care whether one stream is exhausted first or if they take turns.

**Describe alternatives you've considered**

I could abstract it out so that there are two constraints involved, but i've already had to slice one conceptual constraint up into about four different parts, it's starting to get a bit messy.

**Additional context**
I think this is a duplicate of https://stackoverflow.com/questions/69380060/is-there-a-way-to-append-or-union-two-constraint-streams but I couldn't find the optaplanner jira mentioned, or an equivalent here.

**Comment by triceo** [comment]
What a coincidence, `concat` was just delivered in Timefold Solver 1.3.0 last week.
But thanks for reporting anyway!
