### ISSUE TITLE
Project job scheduling - UI not refreshing

### ISSUE THREAD

**Issue by mcimbora** [TimefoldAI/timefold-solver#368]
**Description**
The UI does not seem to refresh. The original state remains displayed all the time.
The solver is running fine.

```
12:23:59.603 [l-1-thread-1] DEBUG     LS step (0), time spent (417), score (-55hard/168medium/-26soft), new best score (-55hard/168medium/-26soft), accepted/selected move count (4/4), picked move (Allocation-39 {ExecutionMode-103 -> ExecutionMode-105}).
12:23:59.604 [l-1-thread-1] DEBUG     LS step (1), time spent (418), score (-50hard/168medium/-26soft), new best score (-50hard/168medium/-26soft), accepted/selected move count (4/4), picked move (Allocation-65 {ExecutionMode-173 -> ExecutionMode-175}).
12:23:59.605 [l-1-thread-1] DEBUG     LS step (2), time spent (419), score (-47hard/168medium/-26soft), new best score (-47hard/168medium/-26soft), accepted/selected move count (4/4), picked move (Allocation-67 {ExecutionMode-179 -> ExecutionMode-181}).
```

![image](https://github.com/TimefoldAI/timefold-solver/assets/4274233/de312a31-eb0b-4dc9-a77f-a020514d8afd)

**Expected behavior**
The UI gets refresh refreshed to reflect the current solution state

## Environment

**Timefold Solver Version or Git ref**: 
34e7d07e490e9b9f349e35a85092597c063957eb

**Output of `java -version`:**
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode)

**Output of `uname -a` or `ver`:**
Darwin localhost 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64

**Comment by triceo** [comment]
I can confirm that there is a problem there.
Through `git bisect` I've tracked it down to this commit: 5ddbcf18865cab8e2daf916eda836b4b53153c3b

Now the hard part. What did I break?
