### ISSUE TITLE
Investigate use of ScoreAnalysis inside score corruption analysis

### ISSUE THREAD

**Issue by triceo** [TimefoldAI/timefold-solver#391]
In this issue, we introduced `ScoreAnalysis`:
https://github.com/TimefoldAI/timefold-solver/issues/286

Maybe it could be useful for score corruption analysis too? 
There is a lot of custom and not-so-nice code there.

**Comment by mcimbora** [comment]
Anything that helps debugging the score corruption will be useful. My other idea is:
- state of the solution before the move
- state of the solution after the move
- state of the solution after the undo move

**Comment by mcimbora** [comment]
Could be even dumping these JSON files to a filesystem.

**Comment by triceo** [comment]
I moved the other comments to a new issue, as that is still useful feedback, but not what I wanted to do short-term in this issue.
