### ISSUE TITLE
A Spring Boot starter should bring spring-boot-starter

### ISSUE THREAD

**Issue by snicoll** [TimefoldAI/timefold-solver#393]
**Describe the bug**
When adding `timefold-solver-spring-boot-starter`, it should bring the bare minimum for a Spring Boot application to start. It doesn't and trying to start or compile an app fails.

**Expected behavior**
Adding the starter only should provide the bare minimum for a project to compile and start. See also [this note](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.developing-auto-configuration.custom-starter.starter-module) in the Spring Boot reference guide.

**Actual behavior**
app doesn't compile

**To Reproduce**
Create an app on start.spring.io, remove the `spring-boot-starter` that Spring Initializr (now) adds manually and try to compile the ap.

**Comment by triceo** [comment]
Thanks for reporting, @snicoll !

**Comment by snicoll** [comment]
courtesy of @wilkinsona, my report is not 100% accurate. The app will compile because the starter brings `spring-boot` and `spring-boot-autoconfigure` manually. However, the reason why we ask `spring-boot-starter` to be declared, either directly or indirectly, is because it brings the bare minimum for building/starting an app and we'd prefer those decisions to stay in a single place. For instance the starter brings the default logging infrastructure.
