### ISSUE TITLE
Allow for programmatic investigation of score corruptions

### ISSUE THREAD

**Issue by triceo** [TimefoldAI/timefold-solver#399]
Anything that helps debugging the score corruption will be useful. My other idea is:
- state of the solution before the move
- state of the solution after the move
- state of the solution after the undo move

_Originally posted by @mcimbora in https://github.com/TimefoldAI/timefold-solver/issues/391#issuecomment-1787665992_

**Comment by triceo** [comment]
We've just merged https://github.com/TimefoldAI/timefold-solver/pull/433.
This PR includes a new exception which, when caught, may help with this.

**Comment by ge0ffrey** [comment]
+1 to close given that #433 probably fixes the original problem. Let's let that use used in the wild a while before we evaluate if we need to reopen this one again.
