### ISSUE TITLE
Docs: Docs refer to non-existent SolutionManager::getSummary method

### ISSUE THREAD

**Issue by matthiasrsl** [TimefoldAI/timefold-solver#492]
The docs page [Understanding the score](https://timefold.ai/docs/timefold-solver/latest/constraints-and-score/understanding-the-score) in 1.5.0 gives the following code to explain the score:
```
SolutionManager<CloudBalance, HardSoftScore> solutionManager = SolutionManager.create(solverFactory);
System.out.println(solutionManager.getSummary(solution));
```

However, the method `getSummary()` does not exist in `SolutionManager`, the expected behavior is provided by the `explain()` method.

**Comment by matthiasrsl** [comment]
Also in the heat map section, the first listing refers to `SolutionManager.explainScore()` instead of `explain()`.

**Comment by triceo** [comment]
Thanks for reporting! This will be a quick fix.
(Docs website is only updates with a new release, so it will show up there when 1.6.0 becomes available.)
