### ISSUE TITLE
Migration docs to handle Quarkus3/spring3 too: refactor ToLatest9.yml migration recipe

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#5]
Requirements
- Remove the ToLatest9.yml that duplicates the Quarkus 3 upgrade recipe
- Document how to upgrade to TF 1.x from:
-- OP 8 only
-- TF 0.8 only
-- OP 8 + Spring 2 to TF 1 + Spring 3
-- OP 8 + Quarkus 2 to TF 1 + Quarkus 3

Delegate ToLatest9.yml's content of that non-timefold recipes upstream to Quarkus/Spring/Openrewrite, so we don't need to maintain it.

For example to update to TF1 + S3 it would look something like this. Document that:
```
$ mvn org.openrewrite.maven:rewrite-maven-plugin:4.43.0:run \
  -Drewrite.recipeArtifactCoordinates=org.springspring-migration:3.0.6,ai.timefold.solver:timefold-solver-migration:0.8.38 \
  -Drewrite.activeRecipes=org.spring.ToLatest,ai.timefold.solver.migration.ToLatest
```

Related info
Q3: https://quarkus.io/blog/quarkus-3-0-final-released/#upgrading

**Comment by triceo** [comment]
This is not currently on the roadmap; reconsider if we see demand.
