### ISSUE TITLE
Use GHA to send a PR to start.spring.io upon Solver release

### ISSUE THREAD

**Issue by triceo** [TimefoldAI/timefold-solver#516]
Otherwise the Timefold version over there gets stale.

Current situation: Timefold 1.5.0 was released mid december, but spring initializer uses Timefold 1.3.0 (mid oct).

Update the **version** here:
https://github.com/spring-io/start.spring.io/blob/main/start-site/src/main/resources/application.yml#L137

**Comment by zepfred** [comment]
The upgrade to version 1.5.0 was [merged](https://github.com/spring-io/start.spring.io/issues/1383) without a PR, so the automated process may only require an issue to be created. As discussed, we may need to share a matrix of compatible versions for validating dependencies.

**Comment by triceo** [comment]
This couldn't have been tested completely without doing a release.
Therefore the actual test will happen during the release.
