### ISSUE TITLE
When spring-boot releases a new minor/major release, update timefold-solver metadata there

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#518]
When Spring Boot release a new minor/major version (think 3.3.0, 3.4.0, etc), we need to:

-  test our latest release against it (with a CI job) and 
- Update the **compatibilityRange** for timefold-solver with a PR here:
  https://github.com/spring-io/start.spring.io/blob/main/start-site/src/main/resources/application.yml#L137

This is not about when we make a release. For that, see: https://github.com/TimefoldAI/timefold-solver/issues/516 instead.

But how do we get notified of that Spring Boot release?
 Before of after their GA goes out?

Proposal A) Follow "GitHub milestone notification on our project"

Proposal B) When Dependabot comes to us.

**Comment by triceo** [comment]
Unresolved question: what do we do about the minimal supported version? Do we test against every Spring version every time they do a new release?

**Comment by ge0ffrey** [comment]
Yes, we have to. Every 3 months Spring Boot releases (spring every 6 months). But CI can reduce the maintenance cost for us. Dependabot will send us a PR anyway to upgrade main.

**Comment by ge0ffrey** [comment]
Spring Boot 3.2.0. was released on 23 November. It's unclear to me when they moved the default for start.spring.io to 3.2.0. Is that immediately or is there a time window there that gives us a bit more slack?

**Comment by triceo** [comment]
It seems to happen on very short notice.
Anyway... this needs to be monitored and updated automatically.
