### ISSUE TITLE
Can't find import ai.timefold.solver.test.api.score.stream.ConstraintVerifier

### ISSUE THREAD

**Issue by zeppelinux** [TimefoldAI/timefold-solver#553]
**Describe the bug**
used the mvn script to migrate and ended up with compilation error in one of the @QuarkusTest's, everything else looks good.

**Expected behavior**
no compilation errors.

**Actual behavior**
Compilation fails with 
package ai.timefold.solver.test.api.score.stream does not exist 
when compiler tries to resolve the 
@Inject
 ConstraintVerifier<MyPlanningConstraintProvider, MyPlanning> constraintVerifier;

**Comment by triceo** [comment]
@zeppelinux, 

Considering the other issue (https://github.com/TimefoldAI/timefold-solver/issues/553) you reported, it looks like something went wrong during migration. Let's start by first addressing that one.

But just to be sure, please double-check that `timefold-solver-test` is on the classpath.
