### ISSUE TITLE
Move ExperimentalConstraintCollectors to core?

### ISSUE THREAD

**Issue by mcimbora** [TimefoldAI/timefold-solver#60]
ExperimentalConstraintCollectors class provides a nice set of collectors that help formulate consecutive* constraints (e.g. max n consecutive working days) especially for employee rostering use cases.

If I want to use the collectors now, I have 2 options:
- copy the package `ai/timefold/solver/examples/common/experimental/*` to my project
- depend on `examples` module, which pulls in a bunch of transitive dependencies

Is it possible to provide these classes as a part of `core` module? I understand these might change with a new release, but the name clearly indicates this is not a stable API anyway.

TODO before we can do this:

- [x] Figure out a better name for `ConsecutiveInfo`.
- [ ] Figure out an API to supply custom `Point_`, not just `Integer`.
- [x] `ConsecutiveInfo` needs to give access to first and last `Sequence`, not just to `Iterable<Sequence>`.

**Comment by triceo** [comment]
There is a reason why they're still "experimental" - we haven't seen enough people use them in the wild and we don't want to commit to an API that possibly falls down on some major use case. (Our API compatibility promise is very strict and once something becomes API, it will not change.)

That said, I am tempted to do something about this. I myself would like us to finalize this API. I won't give any timelines, but I do intend to reconsider this topic in the foreseeable future.

In the meantime, just copy-paste the collector into your own codebase.

**Comment by mcimbora** [comment]
Thanks @triceo 👍

**Comment by Christopher-Chianelli** [comment]
In regards to "Figure out an API to supply a custom Point_, not integer", we already have that: https://github.com/TimefoldAI/timefold-solver/blob/839f9fd8305736c94c8f58dc6e5a5f3471bdaf9f/examples/src/main/java/ai/timefold/solver/examples/common/experimental/ExperimentalConstraintCollectors.java#L189-L239 . The integer version is a faster specialization of IntervalTree that rely on certain properties of integers that cannot be guaranteed with a custom point type (in particular, the property there does not exist an `y` between `x` and `x+1`).

**Comment by thaspius** [comment]
thanks @triceo
