### ISSUE TITLE
Configured class loader not used when loading services

### ISSUE THREAD

**Issue by marinier** [TimefoldAI/timefold-solver#690]
**Describe the bug**
When creating a `SolverConfig` you can set a class loader on it like this:

```java
solverConfig.setClassLoader(this.getClass().getClassLoader());
```

This class loader eventually gets passed to `ScoreDirectorFactoryFactory::decideMultipleScoreDirectorFactories`, but it is not passed to the `ServiceLoader.load` call on line 69 of `ScoreDirectorFactoryFactory.java`. That is, instead of using the provided class loader, it ends up using the default class loader. In my application, this does not work -- the provided class loader needs to be used.

**Expected behavior**
Uses the class loaded provided by the `SolverConfig` when loading services.

**Actual behavior**
Uses the default class loader when loading services. (Specifically, `ServiceLoader` defaults to `Thread.currentThread().getContextClassLoader()`.)

**To Reproduce**
Reproducing my problem where the service loader fails requires access to the specific environment I'm working in, which is not possible. However, you can easily check which class loader is being used by setting a breakpoint and stepping in the `ServiceLoader.load` call on line 69 of `ScoreDirectorFactoryFactory.java`.

## Environment

**Timefold Solver Version or Git ref**: 

1.7.0

**Output of `java -version`:**

openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)

**Output of `uname -a` or `ver`:**

OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631

## Additional information

The fix should be very simple, as the class loader is already passed as an argument to `ScoreDirectorFactoryFactory::decideMultipleScoreDirectorFactories`. Simply change:

```java
ServiceLoader.load(ScoreDirectorFactoryService.class)
```
 to
```java 
ServiceLoader.load(ScoreDirectorFactoryService.class, classLoader)
```

I'm happy to provide a pull request if desired.

**Comment by triceo** [comment]
Hello @marinier - PRs are welcome. Even if we eventually remove the service loader from constraint streams (as discussed [here](https://github.com/TimefoldAI/timefold-solver/issues/664)), it will still remain for enterprise edition, so this will still make sense.

**Comment by marinier** [comment]
Added a PR here: https://github.com/TimefoldAI/timefold-solver/pull/692
