### ISSUE TITLE
Feat: add SolverConfig.withClassLoader method

### ISSUE THREAD

**Issue by marinier** [TimefoldAI/timefold-solver#691]
**Is your feature request related to a problem? Please describe.**
As described in #690 I need to specify a class loader to use in my application. `SolverConfig` includes a `setClassLoader` method. However, this cannot be chained as part of programmatically constructing a configuration.

**Describe the solution you'd like**
There are "with" methods for other parts of `SolverConfig` that can be chained. I propose adding a `withClassLoader` method so that the class loader can be specified as part of a configuration change.

**Describe alternatives you've considered**
I'm currently using the `setClassLoader` method. However, this does not follow the pattern of the rest of the configuration. It was also harder to discover as doesn't follow the same pattern as other parts of the configuration.

**Additional context**
N/A

**Comment by marinier** [comment]
FYI, it looks like `PlannerBenchmarkConfig` already has a `withClassLoader` method, so modifying `SolverConfig` in this way would be consistent. I'm happy to provide a PR.

**Comment by triceo** [comment]
@marinier As always, pull requests are welcome!
