### ISSUE TITLE
Create automated tests for the shared webjar

### ISSUE THREAD

**Issue by rsynek** [TimefoldAI/timefold-solver#71]
The webjar located in https://github.com/TimefoldAI/timefold-solver/tree/main/tools/webui needs to get automated test coverage to become a reliable component others depend on.

TODO: figure out how to introduce layered coverage (unit tests, component tests, if relevant) for the current mix of UI technologies.

**Comment by triceo** [comment]
The webjar is likely going to be removed instead.
