### ISSUE TITLE
NoChangeMove should support rebase()

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#795]
In mutithreaded solving with a customized CH, a NoChangeMove throws an UnsupportedOperationException because rebase() isn't implemented.

The rebase() method should just return the same or another NoChangeMove instance.

**Comment by Christopher-Chianelli** [comment]
Fixed already: https://github.com/TimefoldAI/timefold-solver/commit/493723e2a465b918dba29cd6e2f99428933a76a4 , which is in Timefold Solver 1.9: https://github.com/TimefoldAI/timefold-solver/releases/tag/v1.9.0
