### ISSUE TITLE
OptaPlanner -> Timefold rewrite script fails

### ISSUE THREAD

**Issue by aioobe** [TimefoldAI/timefold-solver#818]
**Describe the bug**

I'm following [this guide](https://timefold.ai/upgrade-optaplanner-to-timefold) but I'm getting this output:

```
$ curl https://timefold.ai/product/upgrade/upgrade-timefold.gradle > upgrade-timefold.gradle ; gradle -Dorg.gradle.jvmargs=-Xmx2G --init-script upgrade-timefold.gradle rewriteRun -DtimefoldSolverVersion=1.9.0 ; rm upgrade-timefold.gradle
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1092  100  1092    0     0   8057      0 --:--:-- --:--:-- --:--:--  8029
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Expected behavior**
Not crash.

**Actual behavior**
See above.

**To Reproduce**
Unfortunately I can not share my project, but it's a Gradle multi project configuration. I might be able to narrow it down to a minimal repro, but it will probably take me half a day or so to get something that actually compiles.

## Environment

**Timefold Solver Version or Git ref**: 

OptaPlanner 9.44.0.Final

**Output of `java -version`:**

```
$ java -version
java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)
```

**Output of `uname -a` or `ver`:**

```
$ uname -a
Linux -------- 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

## Additional notes

Is there any description of the process if I want to do this manually instead?

**Comment by triceo** [comment]
Hello @aioobe! Sorry to hear that you're having issues. 

We occasionally get reports that the migration script doesn't work, but every time it seems to be a different problem; they only have one thing in common: Gradle.

Every time I try it on my own machine, the script works as expected. Maybe I'm trying it on a project that doesn't trigger some failure condition which other projects do. But unfortunately, it means that I can not reproduce the problem - not before, and unfortunately not now. :-(

What version of Gradle are you using?

**Comment by triceo** [comment]
Wrt. manual upgrade - it shouldn't be too hard:

- Replace OptaPlanner JARs with Timefold JARs.
- Replace `import org.optaplanner` with `import ai.timefold.solver`.
- Hopefully 99 % of things just work this way, and there isn't many things to fix after that.

**Comment by aioobe** [comment]
I appreciate your fast response.

> What version of Gradle are you using?

A very old version. 4.4.1. This is unfortunately the latest version in the Ubuntu repositories. I could upgrade but figured I'd check in here to see if it was a known issue. (For my actual project I'm using the `gradlew` wrapper so I haven't bothered upgrading the system `gradle` binary.)

Thanks for your notes on manual upgrade. I should have read on further down on the migration guide. But your comment summarizes it quite well. I've already started the process.

I will make an attempt to manually upgrade. Since I'm on OptaPlanner 9 (which uses Jakarta instead of javax) I don't expect much trouble.

Should everything else fail, I'll narrow down my project to a minimal reproducer so we can sort this out for future migrators.

I'll report back later today.

**Comment by aioobe** [comment]
### XML namespace

```
<solver xmlns="https://timefold.ai/xsd/solver" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://timefold.ai/xsd/solver https://timefold.ai/xsd/solver/solver.xsd">
```

### Import statements

```
find src/main/java -name '*.java' -exec sed -E -i 's/import( static)? org.optaplanner/import\1 ai.timefold.solver/g' {} +
```

Apply any style fixes (`org.optaplanner...` is alphabetically after any `com...` packages, wheras `ai.timefold...` is before)

### Dependencies

I updated my Gradle dependencies from this...

```
implementation "org.optaplanner:optaplanner-core:9.44.0.Final"
testImplementation "org.optaplanner:optaplanner-test:9.44.0.Final"
```

...to this:

```
implementation "ai.timefold.solver:timefold-solver-core:1.9.0"
testImplementation "ai.timefold.solver:timefold-solver-test:1.9.0"
```

### Bavet ScoreDirector

I reference the Bavet ScoreDirector in my code. (Use case described [here](https://stackoverflow.com/questions/76637495/retrieve-problems-for-each-assignment-of-planning-variable) with sample code snippet [here](https://pastebin.com/PrXTT8Nq).) It's on my list to move to the recommendation API, but haven't gotten around doing it. So...

Changed

```
import org.optaplanner.streams.bavet.BavetConstraintStreamScoreDirector;
import org.optaplanner.constraint.streams.bavet.BavetConstraintStreamScoreDirectorFactory;
```

to

```
import ai.timefold.solver.core.impl.score.director.stream.BavetConstraintStreamScoreDirector;
import ai.timefold.solver.core.impl.score.director.stream.BavetConstraintStreamScoreDirectorFactory;
```

There's also a new argument to the `BavetConstraintStreamScoreDirector` called `expectShadowVariablesInCorrectState`. I set it to `true` based on the fact that I don't have any shadow variables at the moment. (Reasonable right?)

### EntityDescriptor / BasicVariableDescriptor ordinal

I had some (currently unused) code referencing `EntityDescriptor` and `BasicVariableDescriptor` too. Apparently they got a new parameter called `ordinal` which I don't know how to set. (I don't know how to figure out a solution wide unique value.) I commented out this part of the code since it's unused, but something I'll have to get back to.

### Move thread count

I'm not on enterprise license at the moment, so had to comment out the `<moveThreadCount>` configuration for the time being.

### Deprecation

`cf.forEachIncludingNullVars` is now deprecated, but it seems it's just a naming thing (changed to `cf.forEachIncludingUnassigned`) so no semantical difference?


----

Does this seem like a complete list of necessary changes? Or am I missing something subtle?

**Comment by triceo** [comment]
Ok, piece by piece:

- I never tried Gradle 4.x. It's very likely it will fail. We don't have a minimum required version exactly, but I'm pretty sure it's something that starts with 8.
- Wrt. Bavet: that is now the default, only implementation. You should no longer need to do any hacking to get that. Just use defaults. (The use case should indeed hopefully be solved by the recommendation API.)
- Wrt. `expectShadowVariablesInCorrectState`: This was introduced for the recommendation API, so it is ppossible your use case will run into it. Simple solution is to use the recommendation API.
- Wrt. the ordinal: It is true that there is no correct way to set this from the outside. This is internal API, and we certainly do not expect anyone to be creating instances from the outside; in fact, pretty sure it will break something.

**Comment by aioobe** [comment]
Thanks @triceo. Valuable help as usual. As a follow-up I've posted [this comment](https://github.com/TimefoldAI/timefold-solver/issues/25#issuecomment-2084956753) on a different ticket. If you have a moment, I would very much like to hear your thoughts over there.

Thanks for all the help with this ticket. I think it will serve as a good starting point for anyone using gradle that runs into trouble with the migration.
