### ISSUE TITLE
Node sharing error: could not locate bytecode after alternative build

### ISSUE THREAD

**Issue by storm-TOS** [TimefoldAI/timefold-solver#825]
## Description
When building a Spring project with automatic node sharing enabled using `mvn clean package` and executing using `java -jar`, an exception is thrown:
> java.lang.IllegalArgumentException: Could not locate bytecode for class (class ...ConstraintProvider).

No issue arises when running immediately from IntelliJ IDEA or when executing using `mvn spring-boot:run`. I expect it is just a matter of build configuration; in which case this is not so much a bug report as a request for the documentation to be expanded.

**To Reproduce**
Configure the Spring Boot quickstart example to use automatic node sharing from the Enterprise Edition (i.e. only modify the pom.xml and add a solverConfig.xml). Run `mvn clean package` and `java -jar target/timefold-solver-spring-boot-school-timetabling-quickstart-1.0-SNAPSHOT.jar`.

## Environment

**Timefold Solver Version or Git ref**: 1.9.0 (Enterprise Edition)

**Output of `java -version`:**
> openjdk version "21.0.2" 2024-01-16
> OpenJDK Runtime Environment (build 21.0.2+13-Ubuntu-122.04.1)
> OpenJDK 64-Bit Server VM (build 21.0.2+13-Ubuntu-122.04.1, mixed mode, sharing)

**Output of `uname -a` or `ver`:**
> Linux 6.5.0-28-generic #29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Hats off to this amazing technology. I will probably post another small issue related to node sharing soon.

Groetjes,
Storm

**Comment by triceo** [comment]
Hello @storm-TOS - thank you for reporting this issue.

Unfortunately, it may not be possible for us to solve it without some sort of access to your codebase. We do not have enough information here to be able to understand what is going on.

Please reach out to me (lukas@timefold.ai) and we'll figure out a way forward.

**Comment by triceo** [comment]
Hmm, as I review the steps to reproduce again, I think I may know what's going on.

What happens if you configure node sharing not in solver config, but in properties, as the [docs say](https://docs.timefold.ai/timefold-solver/latest/enterprise-edition/enterprise-edition#automaticNodeSharing)? Does it still fail?

**Comment by storm-TOS** [comment]
Hi @triceo, thank you for your swift reply!
As you suggested, I removed the solverConfig.xml and added the line `timefold.solver.constraint-stream-automatic-node-sharing=true` to the application.properties. I get the exact same behavior: no issues with `mvn spring-boot:run`, but the "could not locate bytecode" exception when building and running from .jar.

I will send you an email soon!
