### ISSUE TITLE
Exception thrown when using enum switch with automatic node sharing

### ISSUE THREAD

**Issue by storm-TOS** [TimefoldAI/timefold-solver#827]
**Describe the bug**
With automatic node sharing enabled, when trying to use a lambda with an enum switch in a constraint stream, an exception is thrown:
>  java.lang.IllegalArgumentException: Unable to share lambdas because the ConstraintProvider class accesses a protected class (...ConstraintProvider$1).
> Maybe the ConstraintProvider class defines an anonymous inner class?

**To Reproduce**
In any project with automatic node sharing enabled, add an enum in a dedicated file, and add a constraint node making use of this enum in a switch statement/expression. I used the Spring Boot quickstart, modified as in my previous issue #825; added the following enum:
```
public enum SimpleEnum {
    VALUE
}
```
and inserted the following filter in the studentGroupSubjectVariety constraint method:
```
.filter(lesson -> switch (SimpleEnum.VALUE) {
    case VALUE -> true;
})
```

**Workarounds**

- Use `if` statements instead of a switch
- Extract the lambda to a new static method inside the enum
- Make the enum an inner class of the constraint provider

## Environment
The same as in issue #825 

I'm not sure whether this can be solved at all, or if it is something insurmountable from within the Java internals; I'm mostly fascinated by what might be going on behind the scenes here. In any case, a remark in the docs could be nice.

**Comment by triceo** [comment]
We've investigated this and it turns out that switching on an enum generates an internal protected class, which is something our bytecode manipulation under Spring won't be able to handle. (It works perfectly with Quarkus, which allows us to do this work ahead of time, before the classes are loaded.)

Therefore we'll be closing this issue without fixing it. But we're improving our error messages at least.

**Comment by storm-TOS** [comment]
I expected something of the sort, but interesting that Quarkus does allow it - thanks for sharing!
