### ISSUE TITLE
Exception thrown when concatenating constraint streams filtered by planning variables

### ISSUE THREAD

**Issue by storm-TOS** [TimefoldAI/timefold-solver#828]
**Describe the bug**
When creating a stream of entities, filtering based on a planning variable, and then concatenating with a stream based on the same entity class, the following exception is thrown upon solving:
>  Impossible state: The tuple (DEAD) in node (ConcatUniUniNode-1@1) is in an unexpected state (DEAD).

For instance, I added the following constraint to the Spring Boot quickstart:
```
constraintFactory.forEach(Lesson.class)
        .filter(lesson -> lesson.getRoom().getName().equals("Room A"))
        .concat(constraintFactory.forEach(Lesson.class))
        .penalize(HardSoftScore.ofSoft(1))
        .asConstraint("concat")
```
The exception only occurs when filtering based on a planning variable, and only when filtering non-trivially (meaning that some entities are filtered out and some are passed on, instead of blocking either everything or nothing at all). Perhaps this exception only pops up in constraints that could and should be designed differently (the example above obviously does not make sense semantically), but even then, a more helpful error message would be welcome.

## Environment

**Timefold Solver Version or Git ref**: 1.9.0 (Community Edition)

**Output of `java -version`,**
**Output of `uname -a` or `ver`:**
Same as in #825

**Comment by storm-TOS** [comment]
I figured the same! Luckily our application does not really need it, I just came across it and thought I'd share.

**Comment by triceo** [comment]
And it is much appreciated!
