### ISSUE TITLE
Readme mentions examples that do not exist

### ISSUE THREAD

**Issue by odrotbohm** [TimefoldAI/timefold-solver#889]
The build from source section mentions an `examples` folder in step 4 that does not exist.

**Comment by triceo** [comment]
Thanks, @odrotbohm! Well spotted.

**Comment by triceo** [comment]
The examples no longer exist. We now use [the quickstarts](https://github.com/TimefoldAI/timefold-quickstarts/) exclusively, and the README already links to them.

**Comment by odrotbohm** [comment]
Ahh, lovely. I did miss that. Thanks! 🙇
