### ISSUE TITLE
Error reporting no such method when migrating from Optaplanner to Timefold

### ISSUE THREAD

**Issue by jummybean** [TimefoldAI/timefold-solver#91]
The migration from Optaplanner to Timefold may be out of date. When using the following command

./gradlew --info -Dorg.gradle.jvmargs=-Xmx2G --init-script upgrade-timefold.gradle rewriteRun -DtimefoldSolverVersion=0.8.39

to update the basic timetabling problem through gradle, I received the following error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rewriteRun'.
> java.lang.RuntimeException: Error while visiting src/main/java/com/example/timetable/constraints/TimeTableConstraintProvider.java: java.lang.NoSuchMethodError: 'org.openrewrite.java.JavaTemplate$Builder org.openrewrite.java.JavaTemplate.builder(java.util.function.Supplier, java.lang.String)'
    ai.timefold.solver.migration.v8.AsConstraintRecipe$2.visitExpression(AsConstraintRecipe.java:272)
    ai.timefold.solver.migration.v8.AsConstraintRecipe$2.visitExpression(AsConstraintRecipe.java:214)
    org.openrewrite.java.JavaVisitor.visitMethodInvocation(JavaVisitor.java:835)
    org.openrewrite.java.JavaIsoVisitor.visitMethodInvocation(JavaIsoVisitor.java:224)
    org.openrewrite.java.JavaIsoVisitor.visitMethodInvocation(JavaIsoVisitor.java:30)
    org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3706)
    org.openrewrite.java.tree.J.accept(J.java:59)
    org.openrewrite.TreeVisitor.visit(TreeVisitor.java:278)
    ...

It looks like the signature of the JavaTemplate.builder method was changed a couple of weeks back. There doesn't seem to be a builder method that takes two parameters anymore in the most recent version of OpenRewrite.

**Comment by triceo** [comment]
Thanks for reporting!

There was indeed a major new release of OpenRewrite recently. I am a bit surprised that, somehow, we're already consuming the new release even though we have not upgraded to it yet.
Something to investigate.

**Comment by jummybean** [comment]
Can verify the updated migration version in your reply worked fine. I had to update the Optaplanner version in my build.gradle to the appropriate Timefold version, but that's mostly to be expected. Thanks for the quick turnaround.
