### ISSUE TITLE
ArrivalTimeUpdatingVariableListener is not working and not updating arrival time

### ISSUE THREAD

**Issue by sharmas1ddharth** [TimefoldAI/timefold-solver#959]
**Describe the bug**
ArrivalTimeUpdatingVariableListener is not working and not updating arrival time in tests folder

**Expected behavior**
arrival_time variable should not be None

**Actual behavior**
arrival_time variable is None in the output when running tests code to check the output

**To Reproduce**
run test_vehicle_routing.py in tests folder (https://github.com/TimefoldAI/timefold-solver-python/blob/main/tests/test_vehicle_routing.py)

## Environment

**Timefold Solver Version or Git ref**: https://github.com/TimefoldAI/timefold-solver-python/blob/main/tests/test_vehicle_routing.py

**Python version used:** 3.10.14

**Output of `uname -a` or `ver`:** x86_64 GNU/Linux

**Comment by Christopher-Chianelli** [comment]
@sharmas1ddharth you might want to look into using `CascadingUpdateShadowVariable`, a new feature released in [Timefold Solver 1.13.0](https://github.com/TimefoldAI/timefold-solver/releases/tag/v1.13.0) that [the vehicle routing quickstart and test now use](https://github.com/TimefoldAI/timefold-quickstarts/blob/c18de9dfc3ae2ad38446312aeb1a21c61df326f7/python/vehicle-routing/src/vehicle_routing/domain.py#L51-L64).

**Comment by sharmas1ddharth** [comment]
Thanks for the update

**Comment by triceo** [comment]
We have recently fixed a problem with our variable listeners in Python, which leads me to think this issue was fixed as well.

Please give this a try with Timefold Solver 1.15.0 (out in a few weeks) and if it still doesn't work for you, kindly reopen this issue.
